FROM golang:1.9.2
WORKDIR /go/src/github.com/jeefy/hpk/
COPY . .
RUN go get -d -v
RUN cd kapi && \
    go build

FROM alpine:latest
EXPOSE 8000
ENV MONGO_HOST localhost
ENV MONGO_PORT 27017
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=0 /go/src/github.com/jeefy/hpk/kapi/kapi .
ENTRYPOINT ["./kapi"]
