apiVersion: batch/v1
kind: Job
metadata:
  name: {{JOB_NAME}}
spec:
  template:
    metadata:
      name: {{JOB_NAME}}
    spec:
      containers:
      - name: {{JOB_NAME}}
        image: {{IMAGE}}
        command: {{COMMAND}}
        imagePullPolicy: Never
      restartPolicy: Never
  parallelism: {{NUM_NODES}}

  backoffLimit: 4
